sudo: false

os: linux
dist: trusty

language: rust

rust:
  - beta
  - nightly

matrix:
  include:
    - os: linux
      rust: stable
      install:
        - rustup component add clippy
        - rustup component add rustfmt
      script:
        - cargo clippy --all-features -- -D warnings
        - cargo fmt -- --check
        - cargo test --all-features --verbose
  allow_failures:
    - rust: nightly

script:
  - cargo test --all-features --verbose

cache: cargo

env:
  global:
    - CARGO_BUILD_JOBS="2"
